version: "3.1"
services:
  cart:
    image: cart
    build: ./cart/
    ports:
      - "3201:3200"
    depends_on:
      - loms
  loms:
    image: loms
    build: ./loms/
    ports:
      - "3202:3200"
  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
