version: "3.1"

services:
  cart:
    image: cart
    build: ./cart
    ports:
      - "3201:3200"
      - "8081:8080"
    depends_on:
      loms:
        condition: service_started
      postgres:
          condition: service_healthy
    networks:
      - internal

  loms:
    image: loms
    build: ./loms
    ports:
      - "3202:3200"
      - "8082:8080"
    depends_on:
      postgres:
          condition: service_healthy
    networks:
      - internal

  postgres:
    image: postgres:latest
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_CART=${POSTGRES_DB_CART}
      - POSTGRES_DB_LOMS=${POSTGRES_DB_LOMS}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infrastructure/postgres/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: "pg_isready -d ${POSTGRES_DB_CART} -U ${POSTGRES_USER} && \ pg_isready -d ${POSTGRES_DB_LOMS} -U ${POSTGRES_USER}"
      interval: 5s
      timeout: 3s
    networks:
      - internal

volumes:
  postgres-data:
    driver: local

networks:
  internal:
    driver: bridge

  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
