version: "3.1"

services:
  cart:
    image: cart
    build: ./cart
    ports:
      - "3201:3200"
      - "8081:8080"
    depends_on:
      - migration
      - loms
    networks:
      - internal

  loms:
    image: loms
    build: ./loms
    ports:
      - "3202:3200"
      - "8082:8080"
    depends_on:
      - migration
    networks:
      - internal

  migration:
    image: migration
    build:
      context: ./
      dockerfile: ./infrastructure/migration/Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_CART=${POSTGRES_DB_CART}
      - POSTGRES_DB_LOMS=${POSTGRES_DB_LOMS}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal

  postgres:
    image: postgres:latest
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB_CART=${POSTGRES_DB_CART}
      - POSTGRES_DB_LOMS=${POSTGRES_DB_LOMS}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infrastructure/postgres/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: "pg_isready -d ${POSTGRES_DB_CART} -U ${POSTGRES_USER} && \ pg_isready -d ${POSTGRES_DB_LOMS} -U ${POSTGRES_USER}"
      interval: 5s
      timeout: 3s
    networks:
      - internal

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=postgres
      - POOL_MODE=transaction
      - AUTH_TYPE=scram-sha-256
    ports:
      - "5432:5432"
    depends_on:
      - postgres
    networks:
      - internal

  pim-limiter:
    image: limiter
    build: ./limiter
    ports:
      - "3000:3000"
    depends_on:
      - cart
    networks:
      - internal

volumes:
  postgres-data:
    driver: local

networks:
  internal:
    driver: bridge

  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"
