version: "3.1"

services:
  postgres:
    ports:
      - "5432:5432"

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    container_name: pgadmin
#    restart: always
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
#      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
#    ports:
#      - "9090:80"
#    networks:
#      - internal