#!/bin/sh

set -e

psql --username "${POSTGRES_USER}" <<-PGSQL
CREATE DATABASE ${POSTGRES_DB_CART};
GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_DB_CART}" TO "${POSTGRES_USER}";

CREATE DATABASE ${POSTGRES_DB_LOMS};
GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_DB_LOMS}" TO "${POSTGRES_USER}";
PGSQL