server:
  addr_grpc: 0.0.0.0:3200
  addr_http: 0.0.0.0:8080
database:
  dsn: "postgres://user:password@pgbouncer:5432/cart?sslmode=disable"
loms:
  addr: loms:3200
pim:
  addr: http://route256.pavl.uk:8080