server:
  addr_grpc: 0.0.0.0:3200
  addr_http: 0.0.0.0:8080
database:
  dsn: "postgres://user:password@pgbouncer:5432/loms?sslmode=disable"
order:
  cancel_unpaid_timeout: 30
  status_sender:
    brokers:
      - kafka-1:29091
      - kafka-2:29092
      - kafka-3:29093
    topic: order_status
