{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "target", "label": "Host", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Total requests / errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "app_requests_total{instance=\"$target\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "app_errors_total{instance=\"$target\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gogoutines count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$target\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG response time seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "avg(app_response_time_seconds_bucket{instance=\"$target\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}